name: dtrvpn
description: DTR VPN — клиент на базе Mihomo
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  http: ^1.2.2
  yaml: ^3.1.2
  dynamic_color: ^1.7.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  uuid: ^4.5.1
  intl: ^0.20.2
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/
